livereload: true
plugins:
  - jekyll-typescript
typescript:
  build_dir: .tsbuild
  default_source_dir: _ts
  in_source_build:
    - source_dir: _ts
      source_file: hoge.ts
      destination: js/foo.js
      browserify: false
