on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache bundle directory
        # https://blog.freks.jp/github-action-cache/
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install bundler
        run: gem install bundler
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle config build.sassc --disable-march-tune-native # https://github.com/sass/sassc-ruby/issues/146
          if [ ! -e vendor/bundle/.sassc.updated.146 ]; then rm -f vendor/bundle/specifications/sassc-*; touch vendor/bundle/.sassc.updated.146; fi # trigger a rebuild once
          bundle install --jobs 4 --retry 3
      - name: Build with Jekyll
        run: bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
