on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache bundle directory
        # https://blog.freks.jp/github-action-cache/
        # なんか sassc の cache がうまくいかないっぽい:
        # https://github.com/sass/sassc-ruby/issues/146#issuecomment-533005515
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install bundler
        run: gem install bundler
      - name: Bundle install
        run: |
          bundle config specific_platform x86_64-linux
          bundle config --local build.sassc --disable-march-tune-native
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build with Jekyll
        run: bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
      # - name: Deploy to pages_test2
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     external_repository: shwaka/pages_test2
      #     publish_dir: ./_site
      #     publish_branch: master
